feat(bunyan support): add bunyan logging instrumentation
epsagon/epsagon-node pull request #263
Opened 2020-04-27 17:12 UTC by adavidai

2020-04-27 20:00 UTC, galbash requested changes

2020-04-27 20:00 UTC, galbash commented on src/events/bunyan.js
> +        if (tracer.getLogId() === null) {
might be better to call `getLogId()` once and store it in a variable

2020-04-27 20:00 UTC, galbash commented on src/events/bunyan.js
> +        if (tracer.getLogId() === null) {
also might be better just checking `if(log_id)` and not comparing only to null

2020-04-29 16:15 UTC, ronyis commented
I think we should patch the logs only when the user configures to do so.
This flag should be also sent as part of the trace when set.

2020-04-29 16:20 UTC, ranrib commented
> I think we should patch the logs only when the user configures to do so.
> This flag should be also sent as part of the trace when set.

I would prefer to have a flag to disable it, and enable it by default for everyone

2020-04-30 10:08 UTC, galbash approved these changes

2020-04-30 10:17 UTC, merged

2020-04-30 10:20 UTC, ranrib commented
:tada: This PR is included in version 1.61.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon/v/1.61.0)
- [GitHub release](https://github.com/epsagon/epsagon-node/releases/tag/v1.61.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: