feat(lables): support labels inside init
epsagon/epsagon-node pull request #332
Opened 2020-07-21 13:18 UTC by haimrait

2020-07-21 13:37 UTC, ranrib commented on src/tracer.js
> +    config.setConfig({...config.getConfig(), labels: [...config.getConfig().labels, {[key]: value}]})
You've removed the ability to provide complex objects into add label - please return it.

2020-07-21 13:39 UTC, ranrib commented on src/tracer.js
> +    config.getConfig().labels.forEach((label) => {
you can use `entries` to get both key and value at the same time

2020-07-21 13:40 UTC, ranrib commented on src/tracer.js
> +function setLabelsToEvent(tracerObj) {
I would use a more correct name like `addLabelsToTrace` or `setLabelsToRunner`

2020-07-21 13:42 UTC, ranrib commented on src/tracer.js
> +    setLabelsToEvent(tracerObj)
I would move this and the next one a few lines below, since tracerObj can be `undefined`

2020-07-22 05:57 UTC, galbash requested changes
few comments

2020-07-22 05:57 UTC, galbash commented on README.md
> +  labels: [{'key', 'value'}, {'userId', userId}],
Should probably get an object / array of arrays (couples)

2020-07-22 05:57 UTC, galbash commented on src/config.js
> +        config.labels = [...configData.labels];
is it an array or an object? (the default is initialized as an object, but here you set it as an array)

2020-07-22 05:57 UTC, galbash commented on src/tracer.js
> +    config.setConfig({
This change is not valid (we want to preserve the behavior that `addLabel` is per trace basis)

2020-07-22 05:57 UTC, galbash commented on src/tracer.js
> +    setLabelsToEvent(tracerObj);
you can move this to where we set the ecs metadata instead of doing it twice (here and `sendCurrentTrace`)

2020-07-23 06:32 UTC, galbash approved these changes

2020-07-23 09:15 UTC, merged

2020-07-23 09:20 UTC, ranrib commented
:tada: This PR is included in version 1.78.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon/v/1.78.0)
- [GitHub release](https://github.com/epsagon/epsagon-node/releases/tag/v1.78.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: