fix(utils.js): disable events in lambda env
epsagon/epsagon-node pull request #337
Opened 2020-07-30 07:29 UTC by ranrib

2020-07-30 10:59 UTC, galbash requested changes

2020-07-30 10:59 UTC, galbash commented on src/config.js
> +    loggingTracingEnabled: !utils.isLambdaEnv && (process.env.EPSAGON_LOGGING_TRACING_ENABLED || 'TRUE').toUpperCase() === 'TRUE',
please move this check to when selecting the default value and not overriding the final result (if a user explicitly set `EPSAGON_LOGGING_TRACING_ENABLED` it should be set to true)

2020-07-31 10:05 UTC, henperez approved these changes

2020-07-31 10:45 UTC, galbash approved these changes

2020-07-31 11:37 UTC, merged

2020-07-31 11:43 UTC, ranrib commented
:tada: This PR is included in version 1.79.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon/v/1.79.3)
- [GitHub release](https://github.com/epsagon/epsagon-node/releases/tag/v1.79.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: