fix(mongo_wrap_support): change mongo wrapper to be based on shimmer
epsagon/epsagon-node pull request #429
Opened 2021-02-05 15:52 UTC by haimrait

2021-02-05 16:40 UTC, galbash requested changes

2021-02-05 16:40 UTC, galbash commented on src/events/mongodb.js
> +    let patchedCallback;
initialize to `callback` otherwise we risk not calling the user callback in an exception in our instrumentation

2021-02-05 16:48 UTC, galbash approved these changes

2021-02-05 17:00 UTC, enoodle approved these changes

2021-02-05 17:01 UTC, merged

2021-02-08 16:24 UTC, haimrait commented
:tada: This PR is included in version 1.105.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon/v/1.105.1)
- [GitHub release](https://github.com/epsagon/epsagon-node/releases/tag/v1.105.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: